### ISSUE TITLE
Add Product Sans TTF to ISO

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Archlabs-Iso#113]
Need Product Sans font font for the new SLiM themes to display properly.

https://befonts.com/product-sans-font.html

**Comment by erikdubois** [comment]
Google offers many fonts on open source terms. Product Sans is not one of them. Please see www.google.com/fonts.

**Comment by erikdubois** [comment]
You can't get much a clearer [non-] licence than that. – Andrew Leach Sep 2 '15 at 15:42
4	 	
The only way their intentions could be clearer is if they wrote "If you'd like to know if you're allowed to use this font, our licensing terms are as follows" above a picture of Larry Page flipping the bird. – user568458 Sep 2 '15 at 18:15 
  	 	
Aww, that's unfortunate. I got all excited because I found it online and wanted to use it. Since Google doesn't want anyone using it, I'm not going to post the link here. – DavidB Sep 3 '15 at 0:37
add a comment

**Comment by Dobbie03** [comment]
I'll leave the configs as is, leave it up to the user to install the font if they want.

**Comment by erikdubois** [comment]
i did exactly the same with the latest conky al any text any font
i have pasted a link inside the conky where they can download the font
no copyrights issues that way
