### ISSUE TITLE
laptop close

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#120]
then suspend

**Comment by natemaia** [comment]
This may be of use
https://wiki.archlinux.org/index.php/Power_management/Suspend_and_hibernate#Hibernation

Hibernation

In order to use hibernation, you need to create a swap partition or file. You will need to point the kernel to your swap using the resume= kernel parameter, which is configured via the boot loader. You will also need to configure the initramfs. This tells the kernel to attempt resuming from the specified swap in early userspace. These three steps are described in detail below.
About swap partition/file size

Even if your swap partition is smaller than RAM, you still have a big chance of hibernating successfully. According to kernel documentation:
/sys/power/image_size controls the size of the image created by the suspend-to-disk mechanism. It can be written a string representing a non-negative integer that will be used as an upper limit of the image size, in bytes. 

The suspend-to-disk mechanism will do its best to ensure the image size will not exceed that number. However, if this turns out to be impossible, it will try to suspend anyway using the smallest image possible. In particular, if "0" is written to this file, the suspend image will be as small as possible. Reading from this file will display the current image size limit, which is set to 2/5 of available RAM by default.

You may either decrease the value of /sys/power/image_size to make the suspend image as small as possible (for small swap partitions), or increase it to possibly speed up the hibernation process.
Required kernel parameters

The kernel parameter resume=swap_partition has to be used. Either the name the kernel assigns to the 
partition or its UUID can be used as swap_partition. For example:
resume=/dev/sda1
resume=UUID=4209c845-f495-4c43-8a03-5363dd433153
resume=/dev/mapper/archVolumeGroup-archLogicVolume -- example if using LVM

Generally, the naming method used for the resume parameter should be the same as used for the root parameter.
The configuration depends on the used boot loader, refer to Kernel parameters for details.

**Comment by erikdubois** [comment]
added acpid 
acpi powermanagement events
this solved the issue
