### ISSUE TITLE
Editing menu using obmenu

### ISSUE THREAD

**Issue by toola69** [ARCHLabs/Archlabs-Iso#75]
@Dobbie03 @osgyan @erikdubois  
When editing anything in the menu using obmenu as soon as I press save it kicks me out back to the login screen. Can anyone reproduce this?

**Comment by erikdubois** [comment]
no can not reproduce it

**Comment by toola69** [comment]
@erikdubois @Dobbie03 @osgyan 
I've tried everything I can but I am still at a loss people

**Comment by Dobbie03** [comment]
I just reproduced this on my system.

**Comment by toola69** [comment]
@Dobbie03 @osgyan @erikdubois 
Can we just remove this guys.

**Comment by Dobbie03** [comment]
I agree.  Just remove obmenu.  But let's give @erikdubois until the end of the week to see if he can solve the issue.

**Comment by osgyan** [comment]
I just fixed it on phone with Brett, The problem is with LightDM. If you remove/stop lightdm and use xinitrc to start the openbox session, this issue does not happen. We need to either fix LightDM/ Find what is wrong with that or use Slim as a displaymanager, We have not tested if the issue occurs with slim, It is also possible that obmenu is not compatible with any displaymanager, we do not know for sure. So, The resolution now is to not use Lightdm.

Further action:- Investigate Lightdm, Or test with Slim, Or any other Display Manager,  There is no issue if we use xinitrc file and startx to launch the session. It just works fine.
