### ISSUE TITLE
pacman.conf

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#81]
Hide our personal repo so future updates will come from standard aur?
can be put in cleanup.sh if it works

**Comment by Dobbie03** [comment]
I agree, will this make us a proper rolling release?

**Comment by Dobbie03** [comment]
I don't have an issue with our repo being included.

**Comment by erikdubois** [comment]
oomox and a few others are now behind 
since the aur has been updated and not our repo 
i have added issues for that in the repo of archlabs

can you @Dobbie03 experiment with pacman.conf and hashtag out our archlabs server 
i think you will get the updates then from the aur and no more messages that our repo is not up to date

**Comment by osgyan** [comment]
This is a complex one, We need to maintain our Repo at par with AUR. Since the applications we built from AUR and put in repo were installed in Pacman, Yaourt will not detect them as from AUR hence will not auto update them. We need to manage our repo in any case because we source a lot of our programs from AUR. Plus this gives us our own Identity.

**Comment by erikdubois** [comment]
i hear we will need to maintain them...
work....

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by erikdubois** [comment]
we will devide work amongst us
i think i have added three now

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
